
class SQLStatements:

    
    GET_TOPIC_SQL = "SELECT * FROM TOPIC  LIMIT %s ,5"
    
    GET_COMMENT_SQL= "SELECT * FROM COMMENT WHERE COMMENT_TOPIC_ID =%s LIMIT 0 ,5"
    
    GET_COMMENTCEPTION_SQL= "SELECT * FROM COMMENT WHERE COMMENTCEPTION_COMMENTID =%s LIMIT 0 ,5"
    
    
    
    INSERT_INTO_TOPIC_SQL= "INSERT INTO TOPIC(TOPIC_ID,TOPIC_DATA,TOPIC_USERID) VALUES(%s,%s,%s)"
    
    INSERT_INTO_USER_SQL= "INSERT INTO USER(NAME,EMAIL,USER_ID) VALUES(%s,%s,%s) ON DUPLICATE  KEY UPDATE NO_OF_VISITS= NO_OF_VISITS+1"
    
    INSERT_INTO_TOPIC_COMMENT_PRESENT_SQL= "INSERT INTO TOPIC(TOPIC_COMMENT_PRESENT) VALUES(%s)"
    
    INSERT_INTO_COMMENT_SQL= "INSERT INTO COMMENT(COMMENT_ID,COMMENT_DATA,COMMENT_USERID,COMMENT_TOPIC_ID,FOR_AGAINST) VALUES(%s,%s,%s,%s,%s)"
    
    INSERT_INTO_COMMENTCEPTION_SQL ="INSERT INTO COMMENTCEPTION(COMMENTCEPTION_ID,COMMENTCEPTION_DATA,COMMENTCEPTION_USERID,COMMENTCEPTION_COMMENTID) VALUES(%s,%s,%s,%s)"
     
    INSERT_INTO_COMMENTLIKE_SQL ="INSERT INTO COMMENTLIKE (COMMENT_ID, USER_ID ) VALUES (%s,%s)"
    
    INSERT_INTO_COMMENTCEPTIONLIKE_SQL = "INSERT INTO COMMENTCEPTIONLIKE (COMMENTCEPTION_ID, USER_ID) VALUES(%s,%s)"
    
  